BROWSER_TYPE=chrome
APP_URL=https://demo.guru99.com/V4
TESTDATA_FILE_LOCATION=/testdata/TestData.xlsx
TESTDATA_FILE_SHEET_NAME=testdata
BANK_MANAGER_HOME_PAGE_TITLE=Guru99 Bank Manager HomePage
HOME_PAGE_TITLE=Guru99 Bank Home Page